### ISSUE TITLE
TestVulnServer error while build "docker-compose up"

### ISSUE THREAD

**Issue by AnhDungDoan** [GovTech-CSG/PaddingOracleHunter#2]
While I try to build the vuln server, the error occurs: `ImportError: cannot import name 'escape' from 'jinja2' (/usr/local/lib/python3.10/site-packages/jinja2/__init__.py)` . What can I do?

**Comment by GovTech-CSG** [comment]
Hi,

I think the issue is due to the old flask version as they recently drop the escape module from Jinja2. Please kindly set your Flask version in the requirements.txt to Flask==2.1.0 and rebuild should solve the issue.

**Comment by AnhDungDoan** [comment]
many thanks for your support 🥰
